<?php

$labels['forwarding'] = 'Weiterleitung';
$labels['invalidaddress'] = 'Ungültige E-Mail Adresse';
$labels['keepcopies'] = 'Kopie behalten';
$labels['forwardingaddress'] = 'Weiterleitung an diese Adresse(n)';
$labels['forwardingenabled'] = 'Weiterleitung aktivieren';

$messages['forwardingloop'] = 'Diese Weiterleitung wird im Kreis laufen';
$messages['demoaccount'] = 'Dies ist eine Demo. Weiterleitung ist hier nicht möglich.';
?>
